export const farmerCardsData = [
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/ha.jpg',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/dont.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/ha.jpg',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/dont.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/ha.jpg',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/dont.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/farmer.png',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/ha.jpg',
  },
  {
    farmname: '명수팜',
    farmaddress: '경기 이천시 명수로',
    category: '토마토, 무화과, 감자',
    imageUrl: '/dont.png',
  },
];
